In [46]:
import pandas as pd
import sqlite3
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [47]:
# Load cleaned dataset
df = pd.read_csv("../Data/processed/clean_data.csv")

# Connect to SQLite database
conn = sqlite3.connect('../Data/ecommerce.db')

# Load into SQL table
df.to_sql('orders', conn, if_exists='replace', index=False)

3953

In [48]:
# preview of data
query = """
SELECT *
FROM orders
"""

df_view = pd.read_sql_query(query, conn)
df_view

,order_id,order_date,customer_id,product_id,category,quantity,price_per_unit,payment_method,total_order_value,order_status,campaign_id,channel,region,price_without_discount,discount_applied,discount_amount,days_to_delivery
0,2,2025-02-07,2,26146-NL-790,Food - Frozen Meals,413.0,277.0,PayPal,114401.0,Completed,Campaign B,Email Marketing,East,114401.0,0,0.000000,3
1,3,2024-12-02,3,37749-LM-063,Outdoor,62.0,198.0,credit card,12276.0,Completed,Campaign A,Google Ads,West,12276.0,0,0.000000,7
2,4,2025-07-12,4,40389-ZB-335,Food - Soups,663.0,423.0,Apple Pay,280449.0,Completed,Campaign C,Social Media,North,280449.0,0,0.000000,1
3,5,2024-11-27,5,08514-MQ-037,Pets,104.0,244.0,debit card,25376.0,Completed,Campaign A,Google Ads,South,25376.0,0,0.000000,5
4,6,2025-05-31,6,70762-XZ-525,Fitness,875.0,422.0,Apple Pay,369250.0,Returned,Campaign C,Social Media,East,369250.0,0,0.000000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3948,994,2025-03-15,994,61939-JQ-205,Food - Seafood,407.0,81.0,credit card,32967.0,Completed,Campaign B,Email Marketing,East,32967.0,0,0.000000,2
3949,996,2025-01-01,996,06791-ZY-512,Garden,86.0,154.0,Google Pay,13244.0,Completed,Campaign C,Social Media,North,13244.0,0,0.000000,5
3950,997,2025-06-24,997,83634-KO-380,Art Supplies,469.0,427.0,Google Pay,200263.0,Pending,Campaign C,Social Media,South,200263.0,1,45857.238022,10
3951,998,2025-02-03,998,36159-HH-480,Food - Frozen,849.0,298.0,debit card,253002.0,Pending,Campaign B,Email Marketing,East,253002.0,0,0.000000,1
3952,999,2025-06-12,999,17531-UN-740,Food - Desserts,449.0,162.0,credit card,72738.0,Completed,Campaign B,Email Marketing,West,72738.0,0,0.000000,1

KPI's Below

In [ ]:
# Sales Overview
query1 = """
SELECT 
    category,
    SUM(quantity) AS total_quantity,
    SUM(total_order_value) AS revenue,
    (SUM(total_order_value) / COUNT(DISTINCT order_id)) AS average_order_value
FROM orders
GROUP BY category
ORDER BY revenue DESC;
"""

df_view = pd.read_sql_query(query1, conn)
df_view

,category,total_quantity,revenue,average_order_value
0,Kitchen,180484.0,47168749.0,149268.193038
1,Food - Snacks,123448.0,30571554.0,127381.475000
2,Food - Condiments,104300.0,26409964.0,142756.562162
3,Home,98086.0,24532283.0,137051.860335
4,Outdoor,97257.0,24108263.0,149740.763975
...,...,...,...,...
126,Food - Meat Alternatives,583.0,96980.0,48490.000000
127,Food - Cooking Oil,494.0,66690.0,66690.000000
128,Food - Health/Protein,580.0,36540.0,36540.000000
129,Food - Spices & Seasonings,169.0,34889.0,17444.500000
130,Food - Dressing,37.0,777.0,777.000000